version: v1
name: Validation Test
pipeline:
  task_group_1:
    tasks:
      task_1:
        integration: HTTP
        parameters:
          attribute_values: "something"
        depends_on: []
        condition: null
        name: Get HTTP 500
        tags: []
        connection: test_http_status_code_56396
        operation_metadata: null
        treat_failure_as_warning: true
        configuration: null
      task_2:
        integration: TABLEAU_CLOUD
        integration_job: TABLEAU_UPDATE_SUBSCRIPTION
        parameters:
          attribute_values: "something"
        depends_on: []
        condition: null
        name: Tableau Thing
        tags: []
    depends_on: []
    condition: null
    name: ""
schedule: []
sensors: {}
trigger_events: []
webhook:
  enabled: true
  operation_metadata: null
  run_inputs: null
configuration:
  retries: 2
  retry_delay: null
  timeout: null
inputs: null
